### ISSUE TITLE
verifyOrderSignature always returns false ! 

### ISSUE THREAD

**Issue by rahuldamodar94** [trader-xyz/nft-swap-sdk#34]
Hey Guys. 

trying to verify an order on Polygon swapSDK v3 

I am passing 0x0c58c1170f1ded633862a1166f52107490a9c594 as the exchange contract address. Chain ID as 137 

I keep getting false even though the swap goes through. seems to be an issue.

**Comment by johnrjj** [comment]
Thanks Rahul,

You're correct. There was a mismatch between 0x order signatures and typedata signature. This has been fixed in https://github.com/trader-xyz/nft-swap-sdk/pull/35 and I wrote a test to make sure this does not regress again.

I have released `@traderxyz/nft-swap-sdk@0.15.2`(https://github.com/trader-xyz/nft-swap-sdk/releases/tag/v0.15.2) --  if you install that you should be good to go!

Thank you!

**Comment by johnrjj** [comment]
https://github.com/trader-xyz/nft-swap-sdk/releases/tag/v0.15.2

**Comment by rahuldamodar94** [comment]
Appreciate the quick response and fix. Thanks @johnrjj  👍
