### ISSUE TITLE
SDK ready for v1.0.0

### ISSUE THREAD

**Issue by johnrjj** [trader-xyz/nft-swap-sdk#61]
SDK seems stable enough to release a 1.0.0. 

That way we can start semantically verisoning any changes, since we have a good bit of integrators using the sdk now!

**Comment by johnrjj** [comment]
I'll leave this issue open for a few days, and if there is no public comment, will release v1.

**Comment by okorieebube** [comment]
![1](https://user-images.githubusercontent.com/53199415/165668481-091117f8-83e7-43f7-9347-2ef5fd428b56.png)

I'm trying to integrate the sdk but once i try to call 
`await nftSwapperMaker.fillSignedOrder(signedOrder, undefined, {
      gasPrice,
      gasLimit: "500000",
      value: parseEther("0.01"),
    });`
It keeps reverting with the error above. 
I cant really say what the issue is, Probably an error in the contracts?

I'm using NftSwapV3 on the Rinkeby testnet.
Thanks.

**Comment by mahwii44** [comment]
Pls, kindly help wit a youtube tutorial on how to go about using this tool. and also how to use our own UI. This is amazing work
